default:
  http_metas:
    content-type: text/html

  metas:
    title:        Darwin 2
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css, menu.css, /qtip2/dist/jquery.qtip.min.css, ui.datepicker.css, superfish.css]

  javascripts:    [jquery-1.7.1.min.js, jquery-ui-1.8.17.custom.min.js, core.js, /qtip2/dist/jquery.qtip.min.js , catalogue.js, superclick.js ]

  has_layout:     true
  layout:         layout

editSuccess:
  stylesheets: [encod.css]
newSuccess:
  stylesheets: [encod.css]
