default:
  http_metas:
    content-type: text/html

  metas:
    title:        Darwin 2
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css, menu.css, /qtip2/dist/jquery.qtip.min.css]

  javascripts:    [jquery-1.5.1.min.js, jquery.ui.all.min.js, core.js, jquery.hoverIntent.minified.js, superfish.js, supersubs.js, /qtip2/dist/jquery.qtip.min.js , catalogue.js]

  has_layout:     true
  layout:         layout

editSuccess:
  stylesheets: [encod.css]
newSuccess:
  stylesheets: [encod.css]
