logout:
  is_secure:  false
login:
  is_secure:  false
lostPwd:
  is_secure:  false
pwdRenewMail:
  is_secure:  false
renewPwd:
  is_secure:  false
lang:
  is_secure:  false
submit:
  is_secure:  false
