loginSuccess:
  layout:  not_logged
  stylesheets:  [reset.css, content.css, menu_pub.css]
lostPwdSuccess:
  layout:  not_logged
  stylesheets:  [reset.css, content.css, menu_pub.css]
pwdRenewMailSuccess:
  layout:  not_logged
  stylesheets:  [reset.css, content.css, menu_pub.css]
renewPwdSuccess:
  layout:  not_logged
  stylesheets:  [reset.css, content.css, menu_pub.css]
submitSuccess:
  layout:  not_logged
